version: '3.8'

services:
  point-api:
    container_name: ${APP_NAME_API}
    image: point-api/latest
    ports:
      - "8080:8080"
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: point-redis
    hostname: point-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami" # As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
networks:
  default:
    driver: point-default-network