spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      client-id: client-point-api
  redis:
    host: localhost
    port: 6379
    database: 1
